pc_size: 2048
eval_batch_size: 1
dataloader_num_workers: 4
seed: 0 
pred_offset: true
model_type: 'dit_st'
num_inference_steps: 25
model_config:
  n_layers: 12
  latent_dim: 512
  frame_cond: true
  point_embed: true
  mask_cond: false
  pred_offset: true
  num_neighbors: -1  
  floor_cond: true
  max_num_forces: 1
  force_as_token: true
  force_as_latent: false
  gravity_emb: true
  coeff_cond: false
  num_mat: 4
  class_token: true
  transformer_block: SpatialTemporalTransformerBlock
train_dataset:
  category: hf-objaverse-v1
  dataset_path: DATASET_FOLDER
  dataset_list: DATASET_ITEM_LIST_TEST
  has_gravity: true
  max_num_forces: ${model_config.max_num_forces}

  norm_fac: 5
  stage: 'deform'
  mode: 'diff'
  pc_size: 2048
  repeat: 1
  seed: 0
  n_sample_pro_model: 300
  n_frames_interval: 2
  n_training_frames: 24
  batch_size: 20
  overfit: false
